site_name: Overview
nav:
- Theory:
    - 'Theory': 'index.md'
- Technology:
    - 'MkDocs': 'mkdocs.md'
    - 'GIT': 'git.md'
    - 'CSS': 'css.md'
    - 'REST API': 'web_api.md'
    - 'SOAP': 'soap.md'
- Other:
    - 'Netwerkbeheer': 'netwerkbeheer.md'
theme: cinder