site_name: Overview
nav:
- Home: 'index.md'
- Theory:
    - 'Theory': 'concepts.md'
- Technology:
    - 'MkDocs': 'mkdocs.md'
    - 'GIT': 'git.md'
    - 'CSS': 'css.md'
    - 'Web API': 'web_api.md'
- Other:
    - 'Netwerkbeheer': 'netwerkbeheer.md'
theme: cinder