site_name: Overview
nav:
- Home: 'index.md'
- Theory:
    - 'Theory': 'concepts.md'
- Technology:
    - 'Technology': 'technology.md'
    - 'GIT': 'git.md'
- Andere:
    - 'Netwerkbeheer': 'netwerkbeheer.md'
theme: cinder